### ISSUE TITLE
NullPointerException in BetterNpcHighlight causing client to freeze

### ISSUE THREAD

**Issue by mlevatich** [MoreBuchus/buchus-plugins#31]
I am using the Better NPC Highlight plugin for Vardorvis's axes. Every so often, the client completely freezes for a few seconds mid-fight. When I look at Runelite's logs, I see the following crash:

```
2023-08-24 09:39:09 EDT [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.betternpchighlight.BetterNpcHighlightPlugin.onGameTick(BetterNpcHighlightPlugin.java:854)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:211)
	at client.zf(client.java:23677)
	at client.bs(client.java)
	at bm.ay(bm.java:401)
	at bm.run(bm.java:380)
	at java.base/java.lang.Thread.run(Unknown Source)
```

In Better Npc Highlight, the only settings I changed were to highlight the true tiles for IDs 12225 and 12227.

**Comment by MoreBuchus** [comment]
Do you have the slayer plugin enabled?
